title: Grupo de Transporte de la SEIO
author: Grupo de Transporte de la SEIO

url: "https://seio-transporte.github.io"
baseurl: "/"

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Noticias"
   link: ""
 - name: "Eventos"
   link: "events"
 - name: "Miembros"
   link: "members"
